### ISSUE TITLE
Proposal review not working in admin.

### ISSUE THREAD

**Issue by lsilen** [pydata/conf_site#57]
I'm trying to determine how the proposal review process works on the Seattle site and I can't get it to work in admin. I've opened it in the dashboard. I need to give access to the review committee tomorrow.

thanks,
leah

**Comment by jeffsedik** [comment]
@lsilen
 Can you please provide a relevant link for this?

**Comment by lsilen** [comment]
http://seattle.pydata.org/reviews/section/general-sessions/all/

**Comment by codersquid** [comment]
For this, you need to create a team via the django admin, http://london.pydata.org/admin/teams/team/

I'm explaining this from memory so I may be wrong.

Make a team that you can provide a link to so that people can request to be in the team, or there may be a better option.

if you all can't get to this during today, I can try to follow up late this evening.

**Comment by codersquid** [comment]
You'll also need to add relevant permissions to the team.

**Comment by lsilen** [comment]
It looks like you create a group and add permissions, which I did. But I tried to review by clicking on +0 or +1 and I can't get the "vote" to register.

**Comment by codersquid** [comment]
did someone run the symposion django management command to generate the reviewer permissions? I think it happened? but my assumption should be verified.

Be careful, create a _Team_ using the team admin, not a _group_ using the django auth admin.

**Comment by lsilen** [comment]
I just gave your sheila @codersquid account access to the Review Group

**Comment by lsilen** [comment]
Oh, I created a group. Should I somehow undo, that. I see teams at the bottom.

**Comment by jeffsedik** [comment]
@codersquid - we didn't run the symposion django management command to generate the reviewer permissions. @danrjohnson isn't sure what that is. can you run it or provide instructions on what Dan should do?

**Comment by codersquid** [comment]
@danrjohnson it is the _create_review_permissions_ management command.

Here's more info about setting up review permissions and teams
https://groups.google.com/d/msg/pinax-symposion/5dWWuPuqEjc/jZNcu4spzHMJ

**Comment by codersquid** [comment]
I can't run it. I do have an account on the box now, but it is prompting me to change my password, which I do not know.

**Comment by danrjohnson** [comment]
@codersquid I sent along a passwd to use.  Forgot to send that earlier.

**Comment by lsilen** [comment]
Any updates on this?

 Are we going to be able to use the review management?

-Leah


> On May 12, 2015, at 12:36 PM, Dan Johnson <notifications@github.com> wrote:
> 
> @codersquid <https://github.com/codersquid> I sent along a passwd to use. Forgot to send that earlier.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/57#issuecomment-101360737>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449

**Comment by lsilen** [comment]
I have a committee waiting to review proposals and need to know if they can do this using admin. I need to let them know this morning.

-Leah

**Comment by jeffsedik** [comment]
@lsilen
You should be able to use the review management but not yet. Dan will update this issue when he's clear.

**Comment by lsilen** [comment]
That’s great news. Thank you. Can I get an idea of when they can use it? I guess I can always copy and paste the proposals for them to began reading if necessary.

> On May 13, 2015, at 9:44 AM, jeffsedik <notifications@github.com> wrote:
> 
> @lsilen <https://github.com/lsilen>
> You should be able to use the review management but not yet. Dan will update this issue when he's clear.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/57#issuecomment-101694187>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449

**Comment by jeffsedik** [comment]
@lsilen
It's on Dan's plate for today. Hopefully the issue will be resolved soon. Will keep the issue updated and let you and Shelia know if we run into any problems.

**Comment by danrjohnson** [comment]
@lsilen 
I ran the management command and created a team for reviewers:
http://seattle.pydata.org/admin/teams/team/1/

I'm not sure if this should be by invitation or by application, so you may need to adjust this.

**Comment by lsilen** [comment]
Can I just give permissions to the users on the committee under their accounts?

> On May 13, 2015, at 10:50 AM, Dan Johnson <notifications@github.com> wrote:
> 
> @lsilen <https://github.com/lsilen> 
> I ran the management command and created a team for reviewers:
> http://seattle.pydata.org/admin/teams/team/1/ <http://seattle.pydata.org/admin/teams/team/1/>
> I'm not sure if this should be by invitation or by application, so you may need to adjust this.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/57#issuecomment-101722156>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449

**Comment by danrjohnson** [comment]
You can invite them via there email address here: http://seattle.pydata.org/teams/reviewers/

There is a way to create memberships via the django admin, but it will be difficult to isolate which account is which because of the random nature symposian creates usersnames.  I believe this is the only way to do this, but I might be wrong.  @codersquid Does that sound right?

**Comment by lsilen** [comment]
How do I get to that page (other than the link)?

> On May 13, 2015, at 11:00 AM, Dan Johnson <notifications@github.com> wrote:
> 
> You can invite them via there email address here: http://seattle.pydata.org/teams/reviewers/ <http://seattle.pydata.org/teams/reviewers/>
> There is a way to create memberships via the django admin, but it will be difficult to isolate which account is which because of the random nature symposian creates usersnames. I believe this is the only way to do this, but I might be wrong. @codersquid <https://github.com/codersquid> Does that sound right?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/57#issuecomment-101724653>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449

**Comment by lsilen** [comment]
Dan, should I be able to rate them now on: http://seattle.pydata.org/reviews/section/general-sessions/all/?

**Comment by codersquid** [comment]
Yes, the username feature is an annoyance of symposion and there may even
be an open issue about it.

On Wed, May 13, 2015 at 11:00 AM, Dan Johnson <notifications@github.com>
wrote:

> You can invite them via there email address here:
> http://seattle.pydata.org/teams/reviewers/
>
> There is a way to create memberships via the django admin, but it will be
> difficult to isolate which account is which because of the random nature
> symposian creates usersnames. I believe this is the only way to do this,
> but I might be wrong. @codersquid <https://github.com/codersquid> Does
> that sound right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pydata/conf_site/issues/57#issuecomment-101724653>.
>



-- 
shekay@pobox.com

**Comment by codersquid** [comment]
On Wed, May 13, 2015 at 11:12 AM, lsilen <notifications@github.com> wrote:

> How do I get to that page (other than the link)?


It may show up on your dashboard, but I can't see the dashboard to verify
my memory.

Give the link to all of your reviewers so that they can apply to it to be
able to use the review dashboard.


-- 
shekay@pobox.com

**Comment by codersquid** [comment]
On Wed, May 13, 2015 at 11:15 AM, lsilen <notifications@github.com> wrote:

> Dan, should I be able to rate them now on:
> http://seattle.pydata.org/reviews/section/general-sessions/all/?
>

You should be able to.


-- 
shekay@pobox.com

**Comment by lsilen** [comment]
I'm getting an Internal Server error trying to open my account in the dashboard

**Comment by danrjohnson** [comment]
@lsilen I'm looking at this in #60

**Comment by danrjohnson** [comment]
Fixed via https://github.com/pydata/conf_site/commit/3dda1878689c3c8f6081d74f8cde3c2d59b78e98

**Comment by codersquid** [comment]
I changed the team to "by application". That way admins won't need to type email addresses. People can apply directly.

**Comment by lsilen** [comment]
How do I tell them to apply? 
Also, I must be trying to rate proposals incorrectly, I still can't get it to work.

**Comment by danrjohnson** [comment]
I think they just need to login and visit:
http://seattle.pydata.org/teams/reviewers/ 
There is an "Apply" button on the right hand side.

**Comment by lsilen** [comment]
So I should send them that link? they can't get there through their dashboard, correct?

**Comment by danrjohnson** [comment]
I don't think it will display in their dashboard until they become a member

**Comment by lsilen** [comment]
Okay, I've set up an account in a different browser under leahsilen2@gmail.com. I went to http://seattle.pydata.org/teams/reviewers/ and clicked apply. Where do I find that page in admin to accept those who have applied? I can't find it.

**Comment by danrjohnson** [comment]
That same page has a list of Applicants.  I see that account pending there.

**Comment by danrjohnson** [comment]
Sorry. That wasn't ultra clear.  They are visible here: http://seattle.pydata.org/teams/reviewers/

**Comment by lsilen** [comment]
I see it there. But there's no place in admin to access that page? I still can't rate a talk. How do I do that?

**Comment by danrjohnson** [comment]
@lsilen As far as I am aware, that is where you accept/reject members.

I think you review them by using the review tab under an individual talk. There is a form there that you fill out. Is that not working for you ?

**Comment by lsilen** [comment]
Ohhh, I see - under Reviews! I thought that was just where it showed how many have reviewed that talk.

**Comment by danrjohnson** [comment]
@lsilen Are we good on this issue now?

**Comment by lsilen** [comment]
I wanted to test it other than my test on a different browser. I’ve asked someone on the committee to set up an account, then go to http://seattle.pydata.org/teams/reviewers/ <http://seattle.pydata.org/teams/reviewers/> and click apply so that I can make sure it all works. I haven’t heard from him yet though. 

> On May 13, 2015, at 4:10 PM, Dan Johnson <notifications@github.com> wrote:
> 
> @lsilen <https://github.com/lsilen> Are we good on this issue now?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/57#issuecomment-101817320>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449

**Comment by lsilen** [comment]
I just tried to set up a new account under a different email address. I applied to review, then accepted it with the other account. I tried to rate a tutorial and then clicked Submit Review, but it's not showing up on the chart of all tutorials or is registering that it has 1 review.

I have to make sure this is working.

**Comment by jeffsedik** [comment]
@lsilen 
Please supply the credentials for the new account you set up so we can take a look.

**Comment by lsilen** [comment]
leah.silen@continuum.io



> On May 14, 2015, at 9:04 AM, jeffsedik <notifications@github.com> wrote:
> 
> @lsilen <https://github.com/lsilen> 
> Please supply the credentials for the new account you set up so we can take a look.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/57#issuecomment-102046394>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449

**Comment by jeffsedik** [comment]
Password, too, please. Want to log in as that account and see what you're seeing.

**Comment by lsilen** [comment]
Here you go:   data


> On May 14, 2015, at 9:50 AM, jeffsedik <notifications@github.com> wrote:
> 
> Password, too, please. Want to log in as that account and see what you're seeing.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/57#issuecomment-102059974>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449

**Comment by lsilen** [comment]
Can you get the reveiws to show up on your account? I can take a screenshot or share my screen on hangout.

**Comment by jeffsedik** [comment]
No need for a screenshot. Seeing the issue logged in with that account. @danrjohnson - please take a look at this. You can duplicate the issue by viewing http://seattle.pydata.org/teams/reviewers/ when you're logged in as leah.silen@continuum.io / data

**Comment by lsilen** [comment]
I couldn't get it to show up for my other "super user" account either. leah@pydata.org   numfocus

**Comment by lsilen** [comment]
I also need to give the London committee access to see their proposals. Should everything be working on that site?

**Comment by jeffsedik** [comment]
@lsilen - will verify that all the changes applied to Seattle regarding this issue have also been applied to the London site.

**Comment by lsilen** [comment]
Are we close to having Seattle working? I need Seattle working ASAP and London by the end of the day.
Thanks

**Comment by danrjohnson** [comment]
Getting an actual error inside symposian related to review process.  Posting here.
ERROR Internal Server Error: /reviews/review/6/
Traceback (most recent call last):
  File "/www/conf_site/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/www/conf_site/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/www/conf_site/env/local/lib/python2.7/site-packages/symposion/reviews/views.py", line 203, in review_detail
    review.save()
  File "/www/conf_site/env/local/lib/python2.7/site-packages/symposion/reviews/models.py", line 131, in save
    self.proposal.result.update_vote(self.vote)
  File "/www/conf_site/env/local/lib/python2.7/site-packages/symposion/reviews/models.py", line 280, in update_vote
    model._default_manager.filter(pk=self.pk).update(score=ProposalScoreExpression())
  File "/www/conf_site/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 583, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/www/conf_site/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1004, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/www/conf_site/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 775, in execute_sql
    sql, params = self.as_sql()
  File "/www/conf_site/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 967, in as_sql
    (field.__class__.__name__, val.__class__.__name__))
TypeError: Database is trying to update a relational field of type DecimalField with a value of type ProposalScoreExpression. Make sure you are setting the correct relations

**Comment by codersquid** [comment]
I found a post in the symposion mailing list about it, https://groups.google.com/d/msg/pinax-symposion/ryXLRpTiDns/6qPbQWhx5bsJ and there is no follow up there. I'll post a follow up and say we have the same problem.

**Comment by danrjohnson** [comment]
@codersquid  I saw that issue and found a fork of symposion that addressed this issue.

https://github.com/euroscipy/symposion/commits/master

I changed requirements to point to this and was able to submit a review as superuser.  going to test account posted previously.

**Comment by danrjohnson** [comment]
Can confirm working with test account posted earlier.

**Comment by codersquid** [comment]
Thanks @danrjohnson and I submitted an issue to the pinax/symposion project to get it fixed there too https://github.com/pinax/symposion/issues/72

**Comment by danrjohnson** [comment]
@lsilen All the changes applied to seattle are also applied to london as of this writing.

**Comment by lsilen** [comment]
I just tried to vote +1 for Graham Markall's tutorial on London and it's not showing up. this was form my super user account.

**Comment by lsilen** [comment]
I set up a different account and when I try to go to http://london.pydata.org/teams/reviewers/ I get a Page not found error.

**Comment by danrjohnson** [comment]
@lsilen I do need to setup the reviewers account for london, which i will do now

did you fill out comments when you +1'd.  If you don't, it won't accept the +1. (if you click back to the tab you'll see an error)

**Comment by codersquid** [comment]
I don't have time to check this right now, but I remember something happening with scipy last year with respect to voting, here's the issue https://github.com/scipy-conference/SciPy-2014/issues/78

I thought it had to do with a mysql thing, so it might not apply to us since we are using postgresql but please noticed.

**Comment by danrjohnson** [comment]
@codersquid That seems to be the same error as the one listed earlier for Decimal conversion, just with mysql errors instead of postgres errors.  It does seem to be a type conversion problem.

**Comment by codersquid** [comment]
On Thu, May 14, 2015 at 12:46 PM, Dan Johnson <notifications@github.com>
wrote:

> did you fill out comments when you +1'd. If you don't, it won't accept the
> +1. (if you click back to the tab you'll see an error)


might want to open a new issue so that we have a help text to show the user
about comment being required


-- 
shekay@pobox.com

**Comment by codersquid** [comment]
I wonder if the other commit in euroscipy/symposion was an attempt to fix
this?

On Thu, May 14, 2015 at 12:48 PM, Dan Johnson <notifications@github.com>
wrote:

> @codersquid <https://github.com/codersquid> That seems to be the same
> error as the one listed earlier for Decimal conversion, just with mysql
> errors instead of postgres errors. It does seem to be a type conversion
> problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pydata/conf_site/issues/57#issuecomment-102115512>.
>



-- 
shekay@pobox.com

**Comment by lsilen** [comment]
I didn’t comment, but I didn’t on the Seattle one I voted on either and it seemed to register the +1. Do I need to let folks know they have to comment for their rating to count?

**Comment by danrjohnson** [comment]
@lsilen Yes, I think that would be a good idea.  

Also, http://london.pydata.org/teams/reviewers/ is up.

**Comment by lsilen** [comment]
can I delete the votes?

**Comment by danrjohnson** [comment]
@lsilen I've deleted all the reviews off of london and seattle.

**Comment by lsilen** [comment]
Thanks Dan!

**Comment by jeffsedik** [comment]
@lsilen - can we close this issue?

**Comment by lsilen** [comment]
I think so! I just sent out the link for the committee to apply.

> On May 14, 2015, at 4:56 PM, jeffsedik <notifications@github.com> wrote:
> 
> @lsilen <https://github.com/lsilen> - can we close this issue?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/57#issuecomment-102181123>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449
